name: weather_app
description: "Weather Application with API Integration"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # API + Networking
  http: ^1.1.0

  # State Management
  provider: ^6.1.1

  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Local Storage (cache)
  shared_preferences: ^2.2.2

  # Date format
  intl: ^0.18.1

  # Image cache
  cached_network_image: ^3.3.0

  # Env (API key)
  flutter_dotenv: ^5.1.0

  # Check internet
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env